# Atomic File Format
field_separator: "\t"
seq_separator: " "
data_path: /Users/andreaforster/dev/Recbole-Debias/dataset/
dataset: yelp_sample
epochs: 200
learning_rate: 0.001
batch_size: 256
# Common Features
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: checkin_count
# TIME_FIELD: timestamp
seq_len: ~
# Label for Point-wise DataLoader
LABEL_FIELD: label
# NegSample Prefix for Pair-wise DataLoader
NEG_PREFIX: neg_


# Sequential Model Needed
# ITEM_LIST_LENGTH_FIELD: item_length
# LIST_SUFFIX: _list
# MAX_ITEM_LIST_LENGTH: 50
# POSITION_FIELD: position_id

# Knowledge-based Model Needed
# HEAD_ENTITY_ID_FIELD: head_id
# TAIL_ENTITY_ID_FIELD: tail_id
# RELATION_ID_FIELD: relation_id
# ENTITY_ID_FIELD: entity_id

# Selectively Loading
load_col:
    inter: [user_id, item_id, checkin_count]
unload_col: ~
unused_col: ~

# Filtering
rm_dup_inter: ~
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: '[1,inf)'
item_inter_num_interval: '[1,inf)'

eval_args:
    mode: full

eval_neg_sample_args: {'strategy': 'full', 'distribution': 'uniform'}

metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'MAP', 'GiniIndex', 'TailPercentage']
topk: 10
valid_metric: NDCG@10

# Benchmark file
benchmark_filename: ['train','valid','test']

# # special
# INTERVENE_MASK: intervene_mask